### ISSUE TITLE
ctk problem

### ISSUE THREAD

**Issue by MollyZhang** [wstidolph/ctk-core#18] opened 2015-07-01 21:03 UTC
command: `./ctk -h`
error:
`./ctk: line 54: ctk.tgt.searchReads=reads/search: No such file or directory`
`>> ERROR: 1`
`>> ./ctk 54 on_err`

**Comment by wstidolph** [comment] 2015-07-01 21:11
The problem is the unquoted endpoint variables I pasted into the script for future easue-of use (and, didn't test properly, sorry). Until I fix, short-term hack is to un-paste them: just delete lines 52-95

**Comment by wstidolph** [comment] 2015-07-02 02:33
fix committed, it's in alpha.3

**Closed by wstidolph** 2015-07-02 02:33 UTC
